import {createTypes} from 'reduxsauce';

const prefix = 'POSTS/';

export default createTypes(
  `
  FETCH_POST_REQUEST
  FETCH_POST_SUCCESS
  FETCH_POST_FAILURE

  INITIAL_SETUP
  INITIAL_SETUP_SUCCESS
  INITIAL_SETUP_ERROR

  SET_NAVIGATION_REF

  SET_ACTIVE_SCREEN

  SET_CONNECTED
  
  UPDATE_VERSION_INFO
  UPDATE_VERSION_INFO_SUCCESS
  UPDATE_VERSION_INFO_ERROR
`,
  {prefix},
);
